import { Link } from 'react-router-dom'
import { ArrowRight, BookOpen, Brain, CheckSquare, Clock, CalendarDays, BarChart3, Sparkles, ShieldCheck } from 'lucide-react'
const features = [
  [BookOpen, 'Turn notes into understanding', 'Generate a concise summary, three practice questions, and five flashcards from your own course notes.'],
  [CalendarDays, 'Make a plan you can follow', 'Ask the study assistant to organize your open tasks into focused blocks, with room for breaks.'],
  [Clock, 'Give focus some space', 'Pause, resume, and complete Pomodoro sessions. Your focus history feeds your study analytics.'],
  [CheckSquare, 'Keep coursework moving', 'Manage deadlines, subjects, priorities, and progress in a task list that syncs across devices.'],
  [Brain, 'Get unstuck on a concept', 'Ask for a plain-language explanation grounded in the notes you are studying.'],
  [BarChart3, 'See your own progress', 'Track completed tasks, study time, subjects, and activity using your real workspace data.'],
]
export default function LandingPage() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border"><nav className="max-w-6xl mx-auto px-6 py-5 flex items-center justify-between" aria-label="Main navigation"><Link to="/" className="flex items-center gap-2 font-bold text-xl"><Sparkles className="text-primary" />StudySync<span className="text-primary">AI</span></Link><div className="flex gap-5 items-center"><Link to="/login" className="text-sm">Sign in</Link><Link to="/signup" className="rounded-xl bg-primary text-primary-foreground px-4 py-2 text-sm font-semibold">Get started</Link></div></nav></header>
    <main>
      <section className="max-w-6xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-14 items-center">
        <div><p className="inline-flex items-center gap-2 text-primary text-sm font-medium border border-primary/25 rounded-full px-4 py-2 mb-6"><Sparkles size={16} />A calmer way to study</p><h1 className="text-5xl lg:text-6xl font-bold leading-tight tracking-tight">Less scattered.<br /><span className="text-primary">More understood.</span></h1><p className="text-lg text-muted-foreground leading-relaxed mt-6 max-w-lg">Your notes, deadlines, and focus time in one workspace—with a study assistant that helps you turn coursework into a clear next step.</p><div className="flex gap-4 flex-wrap mt-8"><Link to="/signup" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-xl font-semibold">Build my workspace<ArrowRight size={18} /></Link><a href="#features" className="border border-border px-6 py-3 rounded-xl">Explore the tools</a></div><p className="text-xs text-muted-foreground mt-5">Private account • Cloud sync • Your pace</p></div>
        <div className="glass-card rounded-3xl p-6 lg:p-8 border border-primary/20"><div className="flex justify-between items-center mb-7"><div><p className="text-xs text-muted-foreground uppercase tracking-widest">Your study flow</p><h2 className="text-xl font-semibold mt-2">From lecture to clarity</h2></div><BookOpen className="text-primary" /></div>{[['01','Capture','Save the ideas that matter.'],['02','Understand','Generate study materials and explain concepts.'],['03','Practice','Test recall, plan your tasks, and focus.']].map(([number,title,body]) => <div key={number} className="flex gap-4 py-5 border-t border-border"><span className="text-primary font-mono text-sm pt-1">{number}</span><div><h3 className="font-semibold">{title}</h3><p className="text-sm text-muted-foreground mt-1">{body}</p></div></div>)}<div className="mt-5 rounded-xl bg-primary/10 p-4 flex gap-3"><ShieldCheck className="text-primary shrink-0" /><p className="text-sm">Your notes and progress sync securely to your private account. Pick up where you left off.</p></div></div>
      </section>
      <section id="features" className="max-w-6xl mx-auto px-6 pb-20"><p className="text-primary text-sm font-semibold mb-3">ONE CONNECTED WORKSPACE</p><h2 className="text-3xl font-bold mb-10">Tools for the way you actually learn</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{features.map(([Icon,title,body]) => <article key={title} className="glass-card rounded-2xl p-6"><Icon className="text-primary mb-5" /><h3 className="text-lg font-semibold mb-3">{title}</h3><p className="text-sm leading-relaxed text-muted-foreground">{body}</p></article>)}</div></section>
      <section className="max-w-6xl mx-auto px-6 pb-20"><div className="rounded-3xl border border-primary/20 bg-primary/5 p-10 flex flex-col md:flex-row gap-8 justify-between items-start md:items-center"><div><h2 className="text-3xl font-bold">Start with one clear next step.</h2><p className="text-muted-foreground mt-3">Create your account, add your first notes, and build your study rhythm.</p></div><Link to="/signup" className="bg-primary text-primary-foreground rounded-xl px-6 py-3 whitespace-nowrap font-semibold">Get started<ArrowRight className="inline ml-2" size={18} /></Link></div></section>
    </main><footer className="border-t border-border px-6 py-8 text-sm text-muted-foreground max-w-6xl mx-auto flex flex-wrap justify-between gap-4"><span>StudySync AI • Built for better study habits</span><span>AI helps you learn; always verify it against your course material.</span></footer>
  </div>
}
